### ISSUE TITLE
Labeling domains

### ISSUE THREAD

**Issue by doug-lethin-simplisafe** [dnsimple/terraform-provider-dnsimple#105]
Are there any plans for introducing support in Terraform to add labels to a domain similar to what you can do today via the UI?

Maybe the challenge is that it's not available in the API yet?

Thanks.  ( And thanks for writing the plugin)

**Comment by DXTimer** [comment]
Hi @doug-lethin-simplisafe, thank you for taking the time to request the feature. As you have pointed out the API does not support labeling yet and that is the main limitation. While I can't give an exact timeline, we are working on bringing this and other features you've seen in our web app to the API.

I will be sure to update you here when the feature is out.

**Comment by weppos** [comment]
Hi @doug-lethin-simplisafe, thanks for the request. I am going to close this ticket as it depends on a feature we don't have yet on the API, and we will be moving tracking it internally to our feature database.

I will make sure the team will follow up with you should we have any update.
