### ISSUE TITLE
Record cannot be imported

### ISSUE THREAD

**Issue by daniel1302** [dnsimple/terraform-provider-dnsimple#106]
### Terraform Version

v1.4.6

### Affected Resource(s)

- dnsimple_zone_record

### Terraform Configuration Files
```hcl

resource "dnsimple_zone_record" "netlify_aliases_txt" {
  for_each  = local.netlify_dns["aliases"]
  zone_name = each.key
  name      = ""
  type      = "TXT"
  value     = "ALIAS for ${each.value}"
  ttl       = 60
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

```
➜  dns git:(dns-changes) ✗ terraform import 'dnsimple_zone_record.netlify_aliases_txt["some_domain"]' "some_domain_44041155"
╷
│ Error: The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers.
```

**Comment by DXTimer** [comment]
Hi @daniel1302 based on the command you shared I can see that the format of the import ID is likely malformed. You are providing `some_domain_44041155`, instead it should be `some.domain_44041155`. Notice the domain name has the `.` (dot).

> Importing record example.com with record ID 1234
> terraform import dnsimple_zone_record.resource_name example.com_1234

I think we can do some more validation on the ID and provide immediate feedback in case we detect malformed IDs.

**Comment by DXTimer** [comment]
Closing as we haven't heard back from you.

**Comment by DXTimer** [comment]
Closing as we haven't heard back from you.
