### ISSUE TITLE
Implement DNSimple Registrar API

### ISSUE THREAD

**Issue by njoerd114** [dnsimple/terraform-provider-dnsimple#19]
I've got a feature request:
I'd love to be able to register domains via Terraform, DNSimple seems to have an API for Registrar stuff, too... Do you think it'd be possible to implement this into the provider as well?

**Comment by DXTimer** [comment]
We will be working on adding some of the registrar API to our provider in the coming weeks. Look out for updates.

Closing as work is planned for this issue.
