### ISSUE TITLE
Secondary DNS support

### ISSUE THREAD

**Issue by case** [dnsimple/terraform-provider-dnsimple#29]
We'd love to see [Secondary DNS](https://support.dnsimple.com/articles/secondary-dns/) supported in the DNSimple TF provider.

**Comment by weppos** [comment]
Hey Eric! At the time being, secondary DNS is not exposed via API. We'll have to make that available before any integration can be built on top of it.

**Comment by weppos** [comment]
Closing for now as it requires feature development in the app.
