### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by reyreik** [dnsimple/terraform-provider-dnsimple#32]
Would you please make a new release of the dnsimple provider?

The **sandbox flag** feature is very useful for executing terraform tests with the dnsimple sandbox. 

I have built the provider locally, and made use of the sandbox flag feature. But it would be great to not have to copy over the locally built binary, every time that I need to set up a test with our test automation harness.

**Comment by weppos** [comment]
We could not make a release as the repo was still under the Terraform organization, and was not moved to the Registry yet.

It is now https://registry.terraform.io/providers/dnsimple/dnsimple/latest
