### ISSUE TITLE
dnsimple_record removed in minor version release

### ISSUE THREAD

**Issue by muttonhead** [dnsimple/terraform-provider-dnsimple#47]
### Terraform Version
1.0.5

### Affected Resource(s)
Please list the resources as a list, for example:
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "dnsimple_record" "slot_cname" {
   domain = var.dns_zone
   name   = var.slot_cname
   value  = data.kubernetes_service.ingress.load_balancer_ingress[0].hostname
   type   = "CNAME"
   ttl    = 300
 }
```

### Expected Behavior
Breaking changes should result in a major version release

### Actual Behavior
Breaking changes included in a minor version release, this can result in configurations that allow minor versions and patches to break unexpectedly. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by ecomba** [comment]
> ### Terraform Version
> 1.0.5
> 
> ### Affected Resource(s)
> Please list the resources as a list, for example:
> 
> * dnsimple_record
> 
> If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
> 
> ### Terraform Configuration Files
> ```terraform
> resource "dnsimple_record" "slot_cname" {
>    domain = var.dns_zone
>    name   = var.slot_cname
>    value  = data.kubernetes_service.ingress.load_balancer_ingress[0].hostname
>    type   = "CNAME"
>    ttl    = 300
>  }
> ```
> 
> ### Expected Behavior
> Breaking changes should result in a major version release
> 
> ### Actual Behavior
> Breaking changes included in a minor version release, this can result in configurations that allow minor versions and patches to break unexpectedly.
> 
> ### Steps to Reproduce
> Please list the steps required to reproduce the issue, for example:
> 
> 1. `terraform apply`

Thank you Corey!

While moving the provider to the newest SDK and making sure we add some new features to it we decided to change the naming of the `dnsimple_record` to the more appropriate `dnsimple_zone_record` without even thinking about this; so mea maxima culpa.

I will add the `dnsimple_record` configuration back into the provider and cut a new version `0.9.1`. Give me a little time to do this (you'll have it by today!).

**Comment by ecomba** [comment]
Just realised the attributes also changed. Leaving this open till I push the fix.

**Comment by ecomba** [comment]
Sorted this out (finally) with version 0.9.2

**Comment by muttonhead** [comment]
Awesome, thank you Enrique for the quick turn around!
