### ISSUE TITLE
Updating DNS records throws 400 error

### ISSUE THREAD

**Issue by danielcompton** [dnsimple/terraform-provider-dnsimple#5]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- dnsimple_record

### Terraform Configuration Files
```hcl
resource "dnsimple_record" "app_v4" {
  domain = "${var.domain}"
  name   = "${var.name}"
  type   = "${var.type}"
  ttl    = "${var.ttl}"
  value  = "${var.value}"
}
```

### Expected Behavior
1. I updated the name of the domain from test-app to app in my config.
2. I ran terraform apply
3. I expected the update to succeed

### Actual Behavior
I got an error 

```
* dnsimple_record.app_v4: Failed to update DNSimple Record: PATCH https://api.dnsimple.com/v2/<my-account>/zones/<my-domain>/records/12561018: 400 Validation failed
```

I suspect what may be happening is that the provider is detecting a change and trying to do a PATCH, but a PATCH is only valid if the _value_ is changing, not if the _name_ is changing.

### References
Possibly related to https://github.com/terraform-providers/terraform-provider-dnsimple/issues/1?

**Comment by weppos** [comment]
@danielcompton my best guess is that you're right, Terraform is trying to send an update but in this case we can't accept the update as you are effectively creating a record for a different domain name (if I understand correct).

The provider should instead either forbit the operation, or automatically delete the records and re-create them in the new domain.

**Comment by danielcompton** [comment]
I think delete and recreate is the right behaviour here?

**Comment by weppos** [comment]
I am closing this ticket as it is specific to a validation error. We've made [changes to surface the errors](https://github.com/dnsimple/terraform-provider-dnsimple/pull/59), so next time it will be easier to understand the specific issue.
