### ISSUE TITLE
[Feature] Disable DNS hosting and change domain delegation

### ISSUE THREAD

**Issue by anton-kyrylenko** [dnsimple/terraform-provider-dnsimple#54]
Good afternoon. 
Is it possible to disable the hosted_dns domain option   through this provider and set your own dns servers to serve the domain delegation (not subdomain)? Thanks
![dnsimple-delegation](https://user-images.githubusercontent.com/17478421/169008018-4bb503cc-9dfe-4126-9a15-77c2d57abc49.jpg)
![DNS hosted](https://user-images.githubusercontent.com/17478421/169008028-2f0264bb-c2f6-47bc-9c5c-62efa5cc7b46.jpg)

**Comment by DXTimer** [comment]
Hey @anton-kyrylenko, thanks for the feedback.

Enable/Disable DNS Hosting - As it's not something currently supported by our API, I've noted down your interest and will update you when the feature has been implemented.

Change of Delegation i.e. name servers - This feature is currently supported by our API. A good idea will consider this for future development.

**Comment by DXTimer** [comment]
We have just shipped new endpoints to Activate/Deactivate Zones https://github.com/dnsimple/dnsimple-developer/pull/499 enabling us to implement the feature in our resources.

**Comment by DXTimer** [comment]
I'm happy to share that the zone active statement management has been released as part of the new `dnsimple_zone` resource. You can now manage the resolution of your zones.
