### ISSUE TITLE
Terraform DNSimple Prefetch Panic

### ISSUE THREAD

**Issue by laurnts** [dnsimple/terraform-provider-dnsimple#64]
As suggested, this is a separate ticket for the panic issue when using the prefetch option enabled. A similar issue with the previous one I have created https://github.com/dnsimple/terraform-provider-dnsimple/issues/57

Lets me know if a log file is needed, because I believe that was already noted in the previous ticket.

**Comment by DXTimer** [comment]
@laurnts thanks for the report. Could you share your reproduction steps for the issue?

**Comment by DXTimer** [comment]
Closing as stale. Feel free to comment and reopen the issue with more information.
