### ISSUE TITLE
dnsimple_lets_encrypt_certificate resource: docs updates needed

### ISSUE THREAD

**Issue by case** [dnsimple/terraform-provider-dnsimple#68]
The [current docs](https://registry.terraform.io/providers/dnsimple/dnsimple/latest/docs/resources/lets_encrypt_certificate) show the following:

> The following argument(s) are supported:
>
> `domain_id` - (Required) The domain to be issued the certificate for
> `contact_id` - (Deprecated) The contact id for the certificate

But `terraform plan` is saying that a `name = ` argument is required. `auto_renew` is also missing from the Argument Reference list.

It looks like the docs for this resource could use some updating?

**Comment by DXTimer** [comment]
The documentation has been updated, and we are working on automated checks to ensure we never miss updating the documentation again. Thanks for your patience.
