### ISSUE TITLE
dnsimple_lets_encrypt_certificate  defaults now to ECDSA signature algorithm, but RSA should be used for ESX

### ISSUE THREAD

**Issue by ehaselwanter** [dnsimple/terraform-provider-dnsimple#71]
Hi there,

I need to able to order RSA type private keys for dnsimple_lets_encrypt_certificate. The API <https://developer.dnsimple.com/v2/certificates/#issueRenewalLetsencryptCertificate> states that is possible.

How can I either set the default to RSA or configure the Ressource to use RSA?

### Terraform Version

```
❯ terraform -v
Terraform v1.3.7
on darwin_arm64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- dnsimple_lets_encrypt_certificate

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "dnsimple_lets_encrypt_certificate" "esx-1-dc1-cert" {
  domain_id  = "xzy"
  contact_id = var.dnsimple_contact_id
  auto_renew = true
  name       = dnsimple_zone_record.esx-1-dc1.name
}
```

### Expected Behavior

creates a RSA private key 

### Actual Behavior

creates a ECDSA private key. 

### Important Factoids

the default changed and breaker the deployment

### References

By default, a certificate uses ECDSA signature algorithm, but RSA can be used as well if your specific scenario required it.

**Comment by ehaselwanter** [comment]
btw. it is possible to update the cert with a renewal to the api and get working RSA certs

```bash
curl  -H "Authorization: Bearer $TF_VAR_dnsimple_token" \
      -H 'Accept: application/json' \
      -H 'Content-Type: application/json' \
      -X POST \
      -d '{"auto_renew":true,"signature_algorithm":"RSA"}' \
      https://api.dnsimple.com/v2/$TF_VAR_dnsimple_account/domains/the.domain/certificates/letsencrypt/123424/renewals
```

**Comment by DXTimer** [comment]
@ehaselwanter thank you for reporting the issue. We've taken note and will work on extending the provider in the coming weeks.

**Comment by DXTimer** [comment]
The provider has been extended to support selecting which signature algorithm to use when issuing a let's encrypt certificate.

Now you can do:
```hcl
resource "dnsimple_lets_encrypt_certificate" "esx-1-dc1-cert" {
  domain_id  = "xzy"
  auto_renew = true
  name       = dnsimple_zone_record.esx-1-dc1.name
  signature_algorithm = "RSA"
}
```

You can take a look at the resource documentation for an up to date information. 

Closed by https://github.com/dnsimple/terraform-provider-dnsimple/pull/81
