### ISSUE TITLE
v0.17.0 not compatible with Terraform 1.0.0

### ISSUE THREAD

**Issue by cailyoung** [dnsimple/terraform-provider-dnsimple#96]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

`1.0.0`

### Affected Resource(s)

All

### Expected Behavior
What should have happened?

New provider version should work in Terraform versions claimed to be supported by the docs.

### Actual Behavior
What actually happened?

```
22:09:43   Info     |       │ Error: Incompatible provider version
22:09:43   Info     |       │
22:09:43   Info     |       │ Provider "dnsimple/dnsimple" v0.17.0 is not compatible with Terraform
22:09:43   Info     |       │ 1.0.0.
22:09:43   Info     |       │ You need to downgrade to v0.16.3 or earlier. Select it with the following
22:09:43   Info     |       │ constraint:
22:09:43   Info     |       │ 	version = "0.16.3"
22:09:43   Info     |       │
22:09:43   Info     |       │ Terraform checked all of the plugin versions matching the given constraint:
22:09:43   Info     |       │
22:09:43   Info     |       │
22:09:43   Info     |       │ Consult the documentation for this provider for more information on
22:09:43   Info     |       │ compatibility between provider and Terraform versions.
22:09:43   Info     |       │ Alternatively, upgrade to the latest version of Terraform for compatibility
22:09:43   Info     |       │ with newer provider releases.
22:09:43   Info     |       │
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

#93 seems relevant here.

**Comment by wilson-dnsimple** [comment]
Thanks for raising this issue @cailyoung. I had a look into the issue and found that in Terraform versions prior to 1.0.3 did not support automatically downloading protocol v6 providers, as seen in the Terraform changelog [here](https://github.com/hashicorp/terraform/blob/v1.0/CHANGELOG.md#103-july-21-2021) and the issue [here](https://github.com/hashicorp/terraform/pull/29153). As a workaround for this issue, I would suggest using Terraform CLI version 1.0.3 or greater if installing from the registry.

Alternatively, the provider can be downloaded and installed manually like so:

```bash
# Download the provider. Replace `linux_amd64` with the target platform.
curl -fLSs --output provider 'https://github.com/dnsimple/terraform-provider-dnsimple/releases/download/v0.17.0/terraform-provider-dnsimple_0.17.0_linux_amd64.zip'
# Extract the provider.
unzip provider
# Install the provider locally. Replace `linux_amd64` with the target platform.
mkdir -p $HOME/.terraform.d/plugins/registry.terraform.io/dnsimple/dnsimple/0.17.0/linux_amd64/
mv terraform-provider-dnsimple_v0.17.0 $HOME/.terraform.d/plugins/registry.terraform.io/dnsimple/dnsimple/0.17.0/linux_amd64/terraform-provider-dnsimple
```

We recommend using the provider registry directly as it's simpler and keeps it up to date.
