### ISSUE TITLE
Version 0.17.0 of the provider is a breaking change, and should bump the major version number

### ISSUE THREAD

**Issue by adamcrews** [dnsimple/terraform-provider-dnsimple#97]
According to https://github.com/dnsimple/terraform-provider-dnsimple/issues/63 the `dnsimple_record` resource was slated to be removed with v1.0.0 of the provider, but instead it was removed in the 0.17.0 release.  

A breaking change like this should warrant a major version bump rather than a minor version bump.

For future depreciations or major changes like this one, is it possible to only do these with a major version bump?

**Comment by wilson-dnsimple** [comment]
Thanks for raising this issue @adamcrews. We've just released version 1.0.0 which is identical to 0.17.0 but with a stable API which will follow semver strictly. If you are migrating from before version 0.17.0, please read the CHANGELOG to see the changes from that version.
